# MegaLinter Configuration
# Documentation: https://megalinter.io/7.13.0/configuration/

# Performance et mode d'exécution
VALIDATE_ALL_CODEBASE: false
PARALLEL_PROCESS_NUMBER: 4
LOG_LEVEL: INFO

# Linters désactivés (redondants avec nos actions spécialisées)
DISABLE_LINTERS:
  # Sécurité - Nous avons nos propres actions
  - REPOSITORY_TRUFFLEHOG
  - REPOSITORY_TRIVY
  - REPOSITORY_GRYPE
  - REPOSITORY_DEVSKIM
  - REPOSITORY_CHECKOV
  - REPOSITORY_GITLEAKS
  
  # Infrastructure non universelle
  - TEKTON_TEKTON_LINT
  - KUBERNETES_KUBECONFORM
  - ANSIBLE_ANSIBLE_LINT
  - ARM_ARM_TTK
  - CLOUDFORMATION_CFN_LINT
  - TERRAFORM_TFLINT
  - TERRAFORM_TERRASCAN
  - TERRAFORM_TERRAGRUNT
  
  # Linters problématiques
  - COPYPASTE_JSCPD
  - SPELL_CSPELL

# Linters activés pour le code quality
ENABLE_LINTERS:
  # GitHub Actions
  - ACTION_ACTIONLINT
  
  # YAML
  - YAML_YAMLLINT
  - YAML_PRETTIER
  - YAML_V8R
  
  # JSON
  - JSON_JSONLINT
  - JSON_PRETTIER
  
  # JavaScript/TypeScript
  - JAVASCRIPT_ES
  - TYPESCRIPT_ES
  
  # Python
  - PYTHON_FLAKE8
  - PYTHON_BLACK
  
  # Java
  - JAVA_CHECKSTYLE
  
  # Documentation
  - MARKDOWN_MARKDOWNLINT
  
  # Docker
  - DOCKERFILE_HADOLINT
  
  # Liens et dépendances
  - SPELL_LYCHEE
  - GIT_GIT_DIFF
  - REPOSITORY_DUSTILOCK
  - REPOSITORY_SYFT

# Exclusions de fichiers
FILTER_REGEX_EXCLUDE: '(\.git/|node_modules/|\.venv/|__pycache__/|dist/|build/|target/|\.gradle/|\.m2/)'

# Configuration des rapports
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
UPDATED_SOURCES_REPORTER: false
REPORT_OUTPUT_FOLDER: megalinter-reports

# Configuration YAML
YAML_YAMLLINT_CONFIG_FILE: '.yamllint.yml'
YAML_PRETTIER_CONFIG_FILE: '.prettierrc.yml'

# Configuration JavaScript/TypeScript
JAVASCRIPT_ES_CONFIG_FILE: '.eslintrc.json'
TYPESCRIPT_ES_CONFIG_FILE: '.eslintrc.json'

# Configuration Python
PYTHON_FLAKE8_CONFIG_FILE: '.flake8'
PYTHON_BLACK_CONFIG_FILE: 'pyproject.toml'

# Configuration Java
JAVA_CHECKSTYLE_CONFIG_FILE: 'checkstyle.xml'

# Configuration Markdown
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: '.markdownlint.json'

# Configuration Docker
DOCKERFILE_HADOLINT_CONFIG_FILE: '.hadolint.yaml'
