name: Renovate Configuration Setup
description: 'Setup and configure Renovate for automated dependency management'

inputs:
  renovate_schedule:
    description: 'Schedule for Renovate updates'
    required: false
    default: 'before 6am on monday'
  auto_merge_patch:
    description: 'Auto-merge patch updates'
    required: false
    default: 'true'
  auto_merge_dev_deps:
    description: 'Auto-merge dev dependencies'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Setup Renovate Configuration
      shell: bash
      run: |
        echo "🔧 Setting up Renovate configuration for dependency management..."
        
        # Create renovate.json if it doesn't exist
        if [ ! -f "renovate.json" ]; then
          echo "📝 Creating renovate.json configuration..."
          cat > renovate.json << EOF
        {
          "\$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "extends": [
            "config:recommended",
            ":dependencyDashboard",
            ":semanticCommits",
            ":automergeDigest",
            ":automergeMinor"
          ],
          "schedule": ["${{ inputs.renovate_schedule }}"],
          "labels": ["dependencies"],
          "assignees": ["@me"],
          "reviewers": ["@me"],
          "packageRules": [
            {
              "matchDepTypes": ["devDependencies"],
              "automerge": ${{ inputs.auto_merge_dev_deps }}
            },
            {
              "matchUpdateTypes": ["patch"],
              "automerge": ${{ inputs.auto_merge_patch }}
            }
          ],
          "vulnerabilityAlerts": {
            "enabled": true,
            "schedule": ["at any time"]
          }
        }
        EOF
          echo "✅ renovate.json created successfully"
        else
          echo "ℹ️ renovate.json already exists"
        fi
        
        # Create .github/renovate.json5 for more advanced configuration
        mkdir -p .github
        if [ ! -f ".github/renovate.json5" ]; then
          echo "📝 Creating advanced Renovate configuration..."
          cat > .github/renovate.json5 << 'EOF'
        {
          // Advanced Renovate configuration
          "$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "extends": [
            "config:recommended",
            ":dependencyDashboard",
            ":semanticCommits",
            "group:monorepos",
            "group:recommended",
            "workarounds:all"
          ],
          "schedule": ["before 6am on monday"],
          "timezone": "Europe/Paris",
          "labels": ["type: dependencies"],
          "assignees": ["@me"],
          "reviewers": ["@me"],
          "prConcurrentLimit": 5,
          "prHourlyLimit": 2,
          "commitMessagePrefix": "chore(deps):",
          "semanticCommits": "enabled",
          "packageRules": [
            {
              "description": "Auto-merge dev dependencies",
              "matchDepTypes": ["devDependencies"],
              "automerge": true,
              "automergeType": "pr"
            },
            {
              "description": "Auto-merge patch updates",
              "matchUpdateTypes": ["patch"],
              "automerge": true,
              "automergeType": "pr"
            },
            {
              "description": "Group Java dependencies",
              "matchLanguages": ["java"],
              "groupName": "Java dependencies"
            },
            {
              "description": "Group Angular dependencies",
              "matchPackagePatterns": ["^@angular/"],
              "groupName": "Angular dependencies"
            },
            {
              "description": "Group security updates",
              "matchDepTypes": ["dependencies"],
              "matchCurrentVersion": "!/^0\\./",
              "groupName": "Security updates",
              "schedule": ["at any time"]
            }
          ],
          "vulnerabilityAlerts": {
            "enabled": true,
            "schedule": ["at any time"],
            "labels": ["security", "vulnerability"]
          },
          "osvVulnerabilityAlerts": true,
          "dependencyDashboard": true,
          "dependencyDashboardTitle": "🔄 Dependency Dashboard",
          "dependencyDashboardHeader": "This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more."
        }
        EOF
          echo "✅ Advanced Renovate configuration created"
        else
          echo "ℹ️ Advanced Renovate configuration already exists"
        fi
        
        echo ""
        echo "🎯 Renovate setup completed successfully!"
        echo "📋 Next steps to enable automated dependency updates:"
        echo "  1. 🔗 Install the Renovate app on your GitHub repository"
        echo "     👉 https://github.com/apps/renovate"
        echo "  2. 📝 Renovate will create a dependency dashboard issue"
        echo "  3. ✅ Review and merge the onboarding PR"
        echo "  4. 🚀 Enjoy automated dependency updates!"
        echo ""
        echo "📊 Configuration summary:"
        echo "  - Schedule: ${{ inputs.renovate_schedule }}"
        echo "  - Auto-merge patches: ${{ inputs.auto_merge_patch }}"
        echo "  - Auto-merge dev deps: ${{ inputs.auto_merge_dev_deps }}"
        echo "  - Vulnerability alerts: enabled"
        echo "  - Dependency dashboard: enabled"
