name: Code Quality Checks
description: 'Run linting and code quality checks'

inputs:
  sql_lint_path:
    description: 'Path to SQL files for linting'
    required: false
    default: 'models'
  sql_lint_config:
    description: 'Path to SQLFluff config file'
    required: false
    default: '.sqlfluff'
  sql_lint_version:
    description: 'SQLFluff version'
    required: false
    default: '3.3.1'
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: composite
  steps:
    - name: Super-linter
      uses: super-linter/super-linter@v7.4.0
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        # Configuration pour éviter les problèmes de branche
        VALIDATE_ALL_CODEBASE: false
        # Utiliser les fichiers modifiés dans le commit/PR
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch || github.ref_name || 'main' }}
        # Désactiver complètement la validation Git
        IGNORE_GITIGNORED_FILES: true
        # Forcer le mode sans validation de branche
        RUN_LOCAL: true
        # Désactiver les vérifications Git qui causent l'erreur
        DISABLE_ERRORS: false
        # Configuration robuste pour toutes les branches
        MULTI_STATUS: false
        ERROR_ON_MISSING_EXEC_BIT: false
        # Utiliser le workspace actuel sans vérification Git
        GITHUB_WORKSPACE: /github/workspace
        # Désactiver seulement les linters problématiques (approche exclusive)
        VALIDATE_JSCPD: false
        VALIDATE_NATURAL_LANGUAGE: false
        VALIDATE_CHECKOV: false
        VALIDATE_GITLEAKS: false
        VALIDATE_TEKTON: false
        VALIDATE_KUBERNETES_KUBECONFORM: false
        VALIDATE_ANSIBLE: false
        VALIDATE_ARM: false
        VALIDATE_CLOUDFORMATION: false
        VALIDATE_TERRAFORM_TFLINT: false
        VALIDATE_TERRAFORM_TERRASCAN: false
        VALIDATE_TERRAFORM_PLAN: false
        # Désactiver la validation Git pour éviter les erreurs de branche
        VALIDATE_GIT: false
        # Format de sortie
        OUTPUT_FORMAT: tap
        OUTPUT_FOLDER: super-linter-output
        OUTPUT_DETAILS: detailed

    - name: Run Codacy Analysis CLI
      uses: codacy/codacy-analysis-cli-action@master

    - name: Run SQL Lint
      if: hashFiles('**/*.sql')
      uses: yu-iskw/action-sqlfluff@v4
      with:
        github_token: ${{ inputs.github_token }}
        reporter: github-pr-review
        sqlfluff_version: ${{ inputs.sql_lint_version }}
        sqlfluff_command: "fix"
        config: "${{ github.workspace }}/${{ inputs.sql_lint_config }}"
        paths: "${{ github.workspace }}/${{ inputs.sql_lint_path }}"
