name: Get Context
description: 'Get project context to determine language and framework'

inputs:
  working-directory:
    description: 'Directory containing the project to analyze'
    required: true
    default: '.'

runs:
  using: composite
  steps:
  - id: project-type
    shell: bash
    run: |
      cd ${{ inputs.working-directory }}
      # Réinitialisation des variables en JSON
      outputs="{ \
        \"java\": false, \
        \"pom\": false, \
        \"gradle\": false, \
        \"angular\": false, \
        \"spring\": false, \
        \"quarkus\": false \
      }"

      # Fonction de détection
      detect_frameworks() {
        local file=$1
        if grep -q "org.springframework.boot" "$file"; then
          outputs=$(echo "$outputs" | jq '. + {"spring": true}')
        fi
        if grep -q "io.quarkus" "$file"; then
          outputs=$(echo "$outputs" | jq '. + {"quarkus": true}')
        fi
      }

      # Détection principale
      if [ -f "pom.xml" ]; then
        outputs=$(echo "$outputs" | jq '. + {"java": true, "pom": true}')
        detect_frameworks "pom.xml"
      elif [ -f "build.gradle" ]; then
        outputs=$(echo "$outputs" | jq '. + {"java": true, "gradle": true}')
        detect_frameworks "build.gradle"
      elif [ -f "angular.json" ]; then
        outputs=$(echo "$outputs" | jq '. + {"angular": true}')
      fi

      # Export final en une seule commande
      echo "outputs=$outputs" >> $GITHUB_OUTPUT
